### PR TITLE
Uninstall module used on PS 1.6 before using this one

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Comment by sarahdib** [comment]
@Quetzacoalt91 
The old searchbar is still install 
Capture d’écran 2020-04-27 à 15 37 44

**Comment by atomiix** [comment]
@sarahdib I think this is working, "Recherches de la boutique" is `statssearch` not `blocksearch`

**Comment by kpodemski** [comment]
@atomiix maybe it would be good to add "Waiting for QA"

**Comment by atomiix** [comment]
@kpodemski you're right, I'm gonna add "Waiting for dev" too as this is a tricky PR to test and should probably be done by a developer

**Comment by atomiix** [comment]
With **blocksearch** installed, **ps_searchbar** not installed:
Capture d’écran 2021-01-27 à 15 44 36
After installing **ps_searchbar**:
Capture d’écran 2021-01-27 à 15 51 51

This PR is QA ✔

**Comment by atomiix** [comment]
Thanks @Quetzacoalt91

**Pull request merged**
