### PR TITLE
Improved displaying of the search bar placeholder

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Search bar is too tight for a polish phrase inside the placeholder
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#27077.
| How to test?  | Follow the issue

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please show us screenshots about what the result in polish, in french, in english, in german, etc? Something to see if your change is legit for all languages and not only this one?

**Comment by kpodemski** [comment]
@PierreRambaud, I'm sure QA will confirm the issue 👍

**Comment by kpodemski** [comment]
@PierreRambaud I've changed the PR title, and it is also QA verified

**Comment by PierreRambaud** [comment]
> @PierreRambaud I've changed the PR title, and it is also QA verified

I understand that the issue is confirmed by the QA team, but you only changed a padding, I don't know how it can handle all languages that have a long placeholder :thinking: 

With your fix I see no difference
image

**Comment by kpodemski** [comment]
@PierreRambaud have you checked in the incognito mode? If you see no difference then it might be browser cache. I've changed the padding, and min-width. I don't know the way to make input automatically scale to the placeholder width ;-) maybe @NeOMakinG does

**Comment by PierreRambaud** [comment]
> @PierreRambaud have you checked in the incognito mode? If you see no difference then it might be browser cache. I've changed the padding, and min-width. I don't know the way to make input automatically scale to the placeholder width ;-) maybe @NeOMakinG does

Ping @NeOMakinG if you have an idea

**Comment by kpodemski** [comment]
ping @NeOMakinG :>

**Comment by kpodemski** [comment]
can you review these changes @NeOMakinG ?

**Review by NeOMakinG — APPROVED** [review]
I've nothing against it, but obviously, it looks like we can't adapt it to every sentence in every language anyway

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
So let's go for QA

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

I have tested this PR. The issue is not fixed when testing on develop and 1782 branches.
image


Please check and feedback!

Thanks!

**Comment by kpodemski** [comment]
@HanaRebaiQA 

The phrase should be `Szukaj w naszym katalogu`, because this is the original translation, we can't make this field automatically adjusted.

Have you tried to clear the cache? Check in the incognito mode? This is the result I have:
https://www.dropbox.com/s/n76u26q6eej3ejr/Zrzut%20ekranu%202022-01-11%20o%2009.21.23.png?dl=0

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

Thanks for your feedback! I checked again on PS1782, PS178x and develop branches with many languages.
I noticed that with reponsive mode, the issue is displayed with some dimensions.
https://watch.screencastify.com/v/THa05WPZlMzpwU8KWypk

**Comment by kpodemski** [comment]
@HanaRebaiQA 

Sorry, it won't work with every screen width because we can't make placeholders flexible. There's just no way to shrink this amount of text in a short input. The goal of this PR was to prevent cutting off the text in the default desktop display.

**Comment by HanaRebaiQA** [comment]
@kpodemski 

So, It's QA :heavy_check_mark: 
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @HanaRebaiQA

**Pull request merged**
