### PR TITLE
Release 2.1.1

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 2.1.1. This version is only compatible with PS 1.7.8 (and higher versions)
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Please perform a standard testing campaign for module release. Only significant change should be https://github.com/PrestaShop/ps_searchbar/pull/10. After install you need to delete the module template override in the theme `themes/classic/modules/ps_searchbar` and clear the cache then

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Capture d’écran 2021-02-05 à 10 22 49
The search icon is missing in 1.7.6.X and 1.7.7.X

**Comment by matks** [comment]
@sarahdib According to https://github.com/PrestaShop/ps_searchbar/pull/25 BUT ps_searchbar 2.1.0 is only compatible with PS 1.7.8+ (so same for v2.1.1)

Let's find out with @atomiix  if we need to release v2.0.2 instead 😢

**Comment by sarahdib** [comment]
Oh ok :) 
I check using develop and there is a little front problem 
https://drive.google.com/file/d/1AXiO4wZ6MUDA9N5P-j5ZRldtaH-MIFEW/view

**Comment by atomiix** [comment]
@matks I think I forgot to answer you but I made a PR so we can release a v2.0.2: https://github.com/PrestaShop/ps_searchbar/pull/31

**Comment by matks** [comment]
🆙 
So ps_searchbar 2.0.1 has been released => this is good for `1.7.7.x` branch

We now have to handle @sarahdib feedback https://github.com/PrestaShop/ps_searchbar/pull/30#issuecomment-777010285

**Comment by matks** [comment]
I wont have the time to continue this topic.

**Pull request closed without merging**
